### ISSUE TITLE
Delegate tracker updates

### ISSUE THREAD

**Issue by hilaryfung** [nprapps/elections24-primaries#107]
- [x] Make sure Michigan is handled properly. The state has a primary on Feb. 27 and a convention on March 2. My understanding is that some delegates will be determined by the Feb. 27 results, but not bound until March 2. As it stands now, if the AP feed allocates any of the Michigan delegates on Feb. 27, then there will be a mismatch between the bar chart and the line chart. Look out for AP guidance over the next month and update the tracker accordingly.
- [x] Once the candidates rack up more delegates — late February? — change the x-axis of the bar chart and the y-axis of the line chart. On each, add a line and annotation at the 1,215 mark.

**Comment by alykat** [comment]
@hilaryfung will keep an eye out for how things change (or don't change) while on call on 2/27.
