### ISSUE TITLE
When only one Senate result is shown, the table should stretch to 100% width

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#156]
Noted by @hilaryfung. We fixed this for House results (https://github.com/nprapps/elections24-primaries/issues/131) but it's still an issue for Senate. Example from the Ohio Senate GOP primary:

![image](https://github.com/nprapps/elections24-primaries/assets/491318/2dc115a0-3df9-415a-86a1-ba533ac21475)

Looking at the markup / css, though, the solution doesn't seem as straightforward.

**Comment by abidishajia** [comment]
I was looking at this bug [here](https://www.npr.org/2024/03/19/1239554686/trump-bernie-moreno-wins-ohio-gop-primary) but can't seem to reproduce it. Has this been fixed?

**Comment by alykat** [comment]
Not fixed. As a quick-fix in the moment, I [applied some inline css](https://www.npr.org/2024/03/19/1239554686/trump-bernie-moreno-wins-ohio-gop-primary) to a div wrapping the embed to force it to a width that would bring it to a smaller breakpoint where result tables would be stacked:

<img width="557" alt="image" src="https://github.com/nprapps/elections24-primaries/assets/491318/e0f323a1-3a04-4bc8-9200-bbe1e10a6b9c">
