### ISSUE TITLE
Get AP testing schedule

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#16]

**Comment by brentajones** [comment]
[2024 AP Testing Schedule](https://apnews.my.salesforce.com/sfc/p/#E0000000Jm3b/a/Qg000000Stnx/D_TVV.XwxiiPVUEa_ufieFxHjGsI6nYZUEYj0M3Us1E)

**Comment by alykat** [comment]
Converted to Google Sheets here: https://docs.google.com/spreadsheets/d/1AV9KaFatiehQjQlH5qRs4_6YDS6VqCDr/edit#gid=1115654768

Low-pri-but-maybe-useful stretch goal: Set up a Slackbot to alert tests in the slack channel based on that spreadsheet 🤔 

And then a link on AP's site to keep an eye on for future updates: https://customerzone.ap.org/cz/s/us-elections
