### ISSUE TITLE
Set up 2024 calendar

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#3]
2020 example: https://apps.npr.org/elections20-primaries/

Open to revisiting the design.

We've been working on a provisional calendar embedded in seamus in the `2024-political-calendar-20230829` graphic for dgnext. The [underlying data spreadsheet](https://docs.google.com/spreadsheets/d/1BcPbmQRLU2T0V78krIC_l9Oex7gcjfYLOeB42PQoYkw/edit#gid=0) would be a good reference.

**Comment by alykat** [comment]
Results-based events on the automated calendar are pulled from the `races` column of the [config sheet](https://docs.google.com/spreadsheets/d/1O9eh7yU5eaK55R4KROdiF_B_I42urTIQllwVOtrhO0M/edit#gid=0). And all other events + label overrides are specified in the `nonraces` sheet.

**Comment by hilaryfung** [comment]
Listing what's left to do:

- [ ] In calendar graphic, fill in all of the squares for multi-day events
- [ ] In calendar graphic on mobile, make sure "next" button gets hidden when December is in view
- [ ] Add ad spots
- [ ] Debounce scroll event
- [ ] Make sure "scroll to month" works smoothly on mobile. This will become relevant after January, when the calendar graphic automatically scrolls to the current month
- [ ] Add party filters, which also serve as a color legend
