### ISSUE TITLE
Update how we're calling the AP API

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#34]
From the AP docs:

> To strengthen the API security, HTTP support and supplying the API key in the request URL are deprecated and will be completely blocked on January 9, 2024.
> 
> All API requests must use HTTPS and supply the API key in the HTTP request header for secure encrypted transmission.
> 
> You MUST review your API implementation and make changes if necessary. For more information, see [API Security Updates](https://developer.ap.org/ap-elections-api/docs/API_Security_Updates.htm).

This may affect how we approach things on stage (which has a cert but it's tricky) and with local development.

Anyway, we have to do this switchover before Iowa.

**Comment by brentajones** [comment]
Updated API calls in dc3455b; this moves the API key to the header. Also bumped URLs to v3. We're already using HTTPS requests. Will retest once deployed to server.
