### ISSUE TITLE
Update color palette

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#39]
The new marketing kit #6 includes some potentially new d/r colors. Update palette for partisan colors, and think about how other colors we use throughout fit with this.

**Comment by alykat** [comment]
Take a look at the palette in the marketing kit and see if that works for our purposes as a starting point for the partisan colors:
https://drive.google.com/drive/u/1/folders/1921PjHmbGxDsKTIJdNq3XRvPeo9oLSQu

**Comment by alykat** [comment]
Candidate colors seem set at this point.

Do we need a good light red / light blue? (Not necessarily for this project, but related offshoots like campfin graphics.)

**Comment by hilaryfung** [comment]
I just realized that there is in fact dark and light red and blue on the results charts! Light red or light blue to fill in the rectangle when the winner is called

**Comment by alykat** [comment]
In case it's useful — here's the chroma.js page i was noodling with for the reds when we were talking through the ad spending chart last week: https://gka.github.io/palettes/#/8|s|c72021|c72021|1|1

![Image](https://github.com/nprapps/elections24-primaries/assets/491318/cfd7321a-bca0-41b4-ae82-598eae56c1b1)
