### ISSUE TITLE
Update ad code and layout

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#4]
- [x] #29 — @brentajones 
- [x] Update sponsorship code based on most recent requests — @brentajones 
- [x] Make sure ad locations match what's needed — @hilaryfung 
- [x] Rework results page layouts so that the content stretches / centers appropriately — @hilaryfung 
- [x] Validate w/ Sponsorship that what we have is correct (including `adUnitString` and `storyID`)

**Comment by alykat** [comment]
With the new ad positions (above/below), we can maybe follow how things are set up with Books We Love:

https://github.com/nprapps/book-concierge/blob/master/src/partials/_sponsorship.html
https://github.com/nprapps/book-concierge/blob/master/src/css/sponsorship.less

And then lines 63 and 121 here:
https://github.com/nprapps/book-concierge/blob/master/src/index.html#L63

**Comment by alykat** [comment]
@hilaryfung points out that we should check with Sponsorship about updated params for this part of the code:

https://github.com/nprapps/elections24-primaries/blob/main/src/partials/_sponsorship.html#L40-L41

**Comment by alykat** [comment]
notes from erica:

we took a look at the primary page and have a bit of feedback for you all on the ad units and the way they are structured:
ad units:
* child ad unit name looks correct!
* for desktop - the first slot looks right, but could the second slot uses the “NPR Secondary” parent ad unit? right now it has the right div, but still under the “NPR” parent ad unit
* looks like mobile is still falling under NPR parent ad unit instead of the mobile ones. could the top ad slot be under the NPR mobile correct parent and the second slot be under NPR mobile secondary? let me know if you need the paths for these and/or desktop secondary. 

sizes:
* let's remove 320x50 on desktop
* could we update the request to be 300x250, 728x90, 970x250 for desktop and 300x250, 320x50 for mobile?
* context for everyone else - we suspect that ordering the sizes from most popular --> least popular optimized yield

**Comment by alykat** [comment]
One page layout thing still to update: Make sure that the footer is centered in a way that lines up with the main page content. Applies to both the calendar and the state pages. 

![Image](https://github.com/nprapps/elections24-primaries/assets/491318/cb699dd0-5de3-479b-993e-dc63aff239dc)

**Comment by hilaryfung** [comment]
Thank you for catching the footer thing! Fixed with [9d6545c](https://github.com/nprapps/elections24-primaries/commit/9d6545cebeaf1d4481f5bd27f602da40d77509d4)

**Comment by alykat** [comment]
Done pending final review from sponsorship

**Comment by alykat** [comment]
Follow-up from sponsorship in a subsequent ticket
