### ISSUE TITLE
Update Census county-level population data

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#60]
This data is used with the county-level election results.

Page footer says:

> Population data are 2013-2017 ACS 5-year estimates

Values are stored in the `fips` sheet of the config spreadsheet.

**Comment by alykat** [comment]
Refreshed and spot-checked all the counties based on 2022 ACS data. I've flagged a few in the `fips` sheet that need another look, including one county-equivalent in Alaska (may not be relevant b/c we don't usually get county-level data for AK) and all of Connecticut (see #61). We're good for Iowa though.

**Comment by hilaryfung** [comment]
I updated Connecticut by summing Census tracts.
I used 2022 ACS 5-Year Estimates: https://data.census.gov/table/ACSDP5Y2022.DP05?g=040XX00US09$1400000
And this crosswalk to match Census tracts to counties: https://github.com/CT-Data-Collaborative/2022-tract-crosswalk
