### ISSUE TITLE
Customizer: Results embeds are not showing up correctly

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#65]
I tried to set up an embed with the following settings:

<img width="1032" alt="image" src="https://github.com/nprapps/elections24-primaries/assets/491318/7854077d-005c-4c67-a49c-bb942d612324">

I don't see any Iowa results in the preview. And I should not (for now at least) be seeing the delegate totals off to the right.

I'm getting these errors in console:

```
VM121 state.js:2375 Uncaught TypeError: _$sidechain_3.registerGuest is not a function
    at VM121 state.js:2375:29
    at VM121 state.js:2551:2
(anonymous) @ VM121 state.js:2375
(anonymous) @ VM121 state.js:2551
VM155 custom.js:1825 Uncaught TypeError: _$sidechain_3.registerGuest is not a function
    at VM155 custom.js:1825:27
    at VM155 custom.js:1860:2
(anonymous) @ VM155 custom.js:1825
(anonymous) @ VM155 custom.js:1860
VM224 custom.js:1825 Uncaught TypeError: _$sidechain_3.registerGuest is not a function
    at VM224 custom.js:1825:27
    at VM224 custom.js:1860:2
(anonymous) @ VM224 custom.js:1825
(anonymous) @ VM224 custom.js:1860
VM234 custom.js:1825 Uncaught TypeError: _$sidechain_3.registerGuest is not a function
    at VM234 custom.js:1825:27
    at VM234 custom.js:1860:2
(anonymous) @ VM234 custom.js:1825
(anonymous) @ VM234 custom.js:1860
VM246 custom.js:1825 Uncaught TypeError: _$sidechain_3.registerGuest is not a function
    at VM246 custom.js:1825:27
    at VM246 custom.js:1860:2
(anonymous) @ VM246 custom.js:1825
(anonymous) @ VM246 custom.js:1860
custom.js:14 Uncaught TypeError: _$sidechain_3.registerGuest is not a function
    at custom.js:14:23
    at _postlude:2:1
```

**Comment by brentajones** [comment]
I fixed the sidechain bug [here](https://github.com/nprapps/elections24-primaries/commit/67b21d9378a52dc39b961e097efe67f0dc83080d), but embeds are still not pulling correct info.

<img width="528" alt="image" src="https://github.com/nprapps/elections24-primaries/assets/1116857/cf6d5ddf-f8b3-4daf-87de-0b89f8be7e41">

**Comment by brentajones** [comment]
Needed to make the [same change in another place](https://github.com/nprapps/elections24-primaries/commit/89cb7c8f278d2fa43e63f97afdf7a82329a1722e). I still think there are a few bugs in here related to the embed generation (where is this getting its text from? also there's still no delegate info for it to load) but at least things show up now.
