### ISSUE TITLE
County results tables are showing statewide %in rather than county %in?

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#76]
<img width="982" alt="image" src="https://github.com/nprapps/elections24-primaries/assets/491318/7a2c4121-2581-4850-a27d-ad86398734b8">

Might also be a good time to check if we're using EEVP consistently everywhere #57

**Comment by brentajones** [comment]
https://github.com/nprapps/elections24-primaries/blob/78c5d5c1f99c74366c0a6bbedd4227c783480acd/src/js/components/results-table/index.js#L161-L178
