### ISSUE TITLE
Allow for custom footnotes by race ID

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#90]
A request from Wash Desk.

Specific to NH Dem presidential primary, we need a footnote to the effect that "Biden isn’t on the ballot in NH but his allies are mounting a write-in campaign there."

I wonder if there's a way to handle this similar to the calls sheet? Race id as key, footnote as value? (This may actually be implemented in the general election rig. For the primaries rig we can have a footnote that appears above both primaries that are happening for a particular seat (specified in the `races` sheet), but since it'd also follow the GOP result table around, it's not quite appropriate to this situation.

Would be good to have ahead of New Hampshire.

**Comment by brentajones** [comment]
Footnotes are only added on elections that fall within the 3-day window run by the `elex` task. They should be added to any matching results page/embed.

**Comment by brentajones** [comment]
Footnotes are added to the JSON file for the race and won't display until then. This happens either when the race is within the window or if alwaysRun is set to TRUE in the spreadsheet.
