### ISSUE TITLE
Condensed view of results from multiple primaries (needed for March 2 and Super Tuesday)

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#97]
This will first be relevant on ~Feb. 8 (NV GOP and VI GOP),~ (crossing out b/c VI isn't being tabulated by AP) on March 2 (Idaho GOP, Missouri GOP, Michigan conventions) and then of course Super Tuesday.

There are some breadcrumbs here for [how it was handled in 2020](https://github.com/nprapps/elections24-primaries/blob/main/src/embeds/results-march-10.html) (for results from a single party).

It gets much more complicated for Super Tuesday (though there's a [single-party example from 2020](https://github.com/nprapps/elections24-primaries/blob/main/src/embeds/super-tuesday.html) we can look at as well).

**Comment by hilaryfung** [comment]
https://github.com/nprapps/elections20-primaries/blob/master/src/embeds/results-march-10.html

**Comment by hilaryfung** [comment]
- [ ] change to red
- [ ] ask wash desk if they want dem results
- [ ] make sure state results links to go the right place
- [ ] check on staging during a super tuesday test
- [ ] create march 2 embed
